### ISSUE TITLE
Monorepo examples

### ISSUE THREAD

**Issue by zomars** [ataylorme/eslint-annotate-action#38]
Would this work with a monorepo out of the box? Should we merge the results of each package in a single json? Any pointers are appreciated.

**Comment by ataylorme** [comment]
@zomars this action expects a single ESLint report JSON file as an input. If you have multiple report files from many subdirectories, as example, you will need to combine them first.

The action could probably be modified to accept many report files, instead of just one, but currently does not support that.

**Comment by zomars** [comment]
I've ended generating reports individually [like this](https://github.com/calcom/cal.com/blob/21867c9cd43b69dfd9b1857cea3291edd56adc03/apps/web/package.json#L20) and then merging them altogether [like this](https://github.com/calcom/cal.com/blob/21867c9cd43b69dfd9b1857cea3291edd56adc03/.github/workflows/lint.yml#L36-L37).

**Comment by ataylorme** [comment]
Thank you for the reply, hopefully it will help someone else.
