### ISSUE TITLE
only-pr-files default to true was a breaking change

### ISSUE THREAD

**Issue by goleary** [ataylorme/eslint-annotate-action#71]
Thanks for this useful project! I noticed something today that I think you should be aware of.

When `only-pr-files` with a default of `true` was added it broke certain lint rules we rely on like `no-unused-modules`. I don't see anything in the release notes about this input and only found it by combing through old issues.

At this point changing it to default `false` would also be a breaking change, so I don't think there's anything to do here other than be aware of future breaking changes.

**Comment by ataylorme** [comment]
Thanks for the note! I will be more careful with breaking changes going forward.

[`3.0.0` has been released](https://github.com/ataylorme/eslint-annotate-action/releases/tag/3.0.0). Please update any references to the `v3` branch instead of `v3-beta`. Make sure to read the Changelog, breaking changes are documented there (GH_TOKEN input has changed)
